name: Build Shared Libraries

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  build-android-so:
    name: Build Android .so
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 1

      - name: Prepare Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r27b-linux.zip
          unzip -q android-ndk-r27b-linux.zip

      - name: Build .so for all ABIs
        run: |
          ./android-ndk-r27b/ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./jni/Android.mk APP_ABI="armeabi-v7a,arm64-v8a,x86,x86_64" -j$(nproc)

      - name: Upload armeabi-v7a
        uses: actions/upload-artifact@v4
        with:
          name: libhev-socks5-tunnel-android-armeabi-v7a.so
          path: libs/armeabi-v7a/libhev-socks5-tunnel.so
          if-no-files-found: error
          retention-days: 5

      - name: Upload arm64-v8a
        uses: actions/upload-artifact@v4
        with:
          name: libhev-socks5-tunnel-android-arm64-v8a.so
          path: libs/arm64-v8a/libhev-socks5-tunnel.so
          if-no-files-found: error
          retention-days: 5

      - name: Upload x86
        uses: actions/upload-artifact@v4
        with:
          name: libhev-socks5-tunnel-android-x86.so
          path: libs/x86/libhev-socks5-tunnel.so
          if-no-files-found: error
          retention-days: 5

      - name: Upload x86_64
        uses: actions/upload-artifact@v4
        with:
          name: libhev-socks5-tunnel-android-x86_64.so
          path: libs/x86_64/libhev-socks5-tunnel.so
          if-no-files-found: error
          retention-days: 5
